# Use postgres/example user/password credentials
version: '3.20'

services:
  db:
    container_name: db
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    container_name: server
    image: server:1
    build:
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      - db
      - adminer
    environment:
      - SERVER_PORT = 8181
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/postgres
